version: '3.8'

services:
  urna:
    build:
      context: ./votacao_sistema/urna
    image: urna_service:latest
    ports:
      - "5000:5000"
    depends_on:
      - agregador
    deploy:
      replicas: 10
      restart_policy:
        condition: any

  agregador:
    build:
      context: ./votacao_sistema/agregador
    image: agregador_service:latest
    deploy:
      restart_policy:
        condition: any
