version: '3.8'

services:
  urna:
    build:
      context: ./votacao_sistema/urna
    container_name: urna_service
    ports:
      - "5000:5000"
    depends_on:
      - agregador
    restart: unless-stopped

  agregador:
    build:
      context: ./votacao_sistema/agregador
    container_name: agregador_service
    restart: unless-stopped
